SELECT DISTINCT E.DEPARTMENT_ID, L.LOCATION_ID, L.STREET_ADDRESS
FROM HR.LOCATIONS L
LEFT JOIN HR.DEPARTMENTS D
  ON L.LOCATION_ID = D.LOCATION_ID
LEFT JOIN HR.EMPLOYEES E
  ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
  WHERE E.DEPARTMENT_ID=(SELECT DEPARTMENT_ID AS "DEPT"
FROM (SELECT E2.DEPARTMENT_ID, COUNT(E2.DEPARTMENT_ID) AS "NO_OF_EMPLOYEES"
FROM HR.EMPLOYEES E2
GROUP BY E2.DEPARTMENT_ID
ORDER BY "NO_OF_EMPLOYEES" DESC)
WHERE ROWNUM=1);